import type { ComponentType } from 'react'
import {
  ExtremeWideIll,
  WideIll,
  FullIll,
  MediumLongIll,
  CowboyIll,
  MediumIll,
  MediumCloseUpIll,
  CloseUpIll,
  ExtremeCloseUpIll,
  TwoShotIll,
  OverShoulderIll,
  InsertIll,
} from './shotSizes'
import {
  EyeLevelIll,
  LowAngleIll,
  HighAngleIll,
  BirdsEyeIll,
  WormsEyeIll,
  DutchAngleIll,
  PovIll,
  ShoulderLevelIll,
} from './angles'
import {
  WideAngleLensIll,
  NormalLensIll,
  TelephotoLensIll,
  ShallowDofIll,
  DeepFocusIll,
  DollyZoomIll,
} from './lens'
import {
  StaticIll,
  PanIll,
  TiltIll,
  DollyIll,
  TruckIll,
  CraneIll,
  HandheldIll,
  SteadicamIll,
  TrackingIll,
  WhipPanIll,
  RackFocusIll,
} from './movement'
import {
  ThreePointIll,
  HighKeyIll,
  LowKeyIll,
  ChiaroscuroIll,
  HardLightIll,
  SoftLightIll,
  PracticalIll,
  RembrandtIll,
  ButterflyIll,
  SilhouetteIll,
} from './lighting'
import {
  WarmPaletteIll,
  CoolPaletteIll,
  TealOrangeIll,
  DesaturatedIll,
  HighContrastIll,
  LowContrastIll,
  MonochromaticIll,
  ComplementaryIll,
  ColorSymbolismIll,
  MotivatedColorIll,
} from './moodColor'

export const ILLUSTRATIONS: Record<string, ComponentType> = {
  // shot sizes
  'extreme-wide': ExtremeWideIll,
  wide: WideIll,
  full: FullIll,
  'medium-long': MediumLongIll,
  cowboy: CowboyIll,
  medium: MediumIll,
  'medium-close-up': MediumCloseUpIll,
  'close-up': CloseUpIll,
  'extreme-close-up': ExtremeCloseUpIll,
  'two-shot': TwoShotIll,
  'over-the-shoulder': OverShoulderIll,
  insert: InsertIll,
  // camera angles
  'eye-level': EyeLevelIll,
  'low-angle': LowAngleIll,
  'high-angle': HighAngleIll,
  'birds-eye': BirdsEyeIll,
  'worms-eye': WormsEyeIll,
  'dutch-angle': DutchAngleIll,
  pov: PovIll,
  'shoulder-level': ShoulderLevelIll,
  // lens
  'wide-angle-lens': WideAngleLensIll,
  'normal-lens': NormalLensIll,
  'telephoto-lens': TelephotoLensIll,
  'shallow-dof': ShallowDofIll,
  'deep-focus': DeepFocusIll,
  'dolly-zoom': DollyZoomIll,
  // movement
  static: StaticIll,
  pan: PanIll,
  tilt: TiltIll,
  dolly: DollyIll,
  truck: TruckIll,
  crane: CraneIll,
  handheld: HandheldIll,
  steadicam: SteadicamIll,
  tracking: TrackingIll,
  'whip-pan': WhipPanIll,
  'rack-focus': RackFocusIll,
  // lighting
  'three-point': ThreePointIll,
  'high-key': HighKeyIll,
  'low-key': LowKeyIll,
  chiaroscuro: ChiaroscuroIll,
  'hard-light': HardLightIll,
  'soft-light': SoftLightIll,
  practical: PracticalIll,
  rembrandt: RembrandtIll,
  butterfly: ButterflyIll,
  silhouette: SilhouetteIll,
  // mood & color
  'warm-palette': WarmPaletteIll,
  'cool-palette': CoolPaletteIll,
  'teal-orange': TealOrangeIll,
  desaturated: DesaturatedIll,
  'high-contrast': HighContrastIll,
  'low-contrast': LowContrastIll,
  monochromatic: MonochromaticIll,
  complementary: ComplementaryIll,
  'color-symbolism': ColorSymbolismIll,
  'motivated-color': MotivatedColorIll,
}
